---
# Lab 1 — Playbook principale
# Prima sessione corso GitOps / Ansible
#
# Esecuzione:
#   ansible-playbook playbook.yml
#   ansible-playbook playbook.yml --check --diff    # dry run
#   ansible-playbook playbook.yml --ask-vault-pass  # con vault
#   ansible-playbook playbook.yml --tags deploy     # solo tag deploy

- name: Lab 1 — Configura webserver nginx
  hosts: all
  become: true

  # Le variabili sono in group_vars/all/vars.yml
  # Le variabili sensibili sono in group_vars/all/vault.yml (cifrato)

#  handlers:
#    - name: Riavvia nginx
#      ansible.builtin.service:
#        name: nginx
#        state: restarted

  tasks:

    # ── Task 1: Installazione ───────────────────────────────────────────────
    - name: Installa nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: true
      tags:
        - install
        - nginx

    # ── Task 2: Directory applicazione ─────────────────────────────────────
    - name: Crea directory applicazione
      ansible.builtin.file:
        path: /var/www/html/myapp
        state: directory
        mode: '0755'
        owner: www-data


    # ── Task 2: Directory applicazione ─────────────────────────────────────
 #   - name: Crea directory applicazione
 #     ansible.builtin.file:
 #       path: /var/www/html/{{ app_name | lower }}
 #       state: directory
 #       mode: '0755'
 #       owner: "{{ app_owner }}"
 #       group: "{{ app_owner }}"
 #     tags:
 #       - install
 #       - config

    # ── Task 3: Servizio ────────────────────────────────────────────────────
    - name: Avvia e abilita nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true
      tags:
        - install
        - nginx

    # ── Task 4: Template HTML ───────────────────────────────────────────────
#    - name: Deploy pagina HTML da template
#      ansible.builtin.template:
#        src: templates/index.html.j2
#        dest: /var/www/html/{{ app_name | lower }}/index.html
#        owner: "{{ app_owner }}"
#        group: "{{ app_owner }}"
#        mode: '0644'
#      notify: Riavvia nginx
#      tags:
#        - deploy
#        - html
